name: Run Chaos Tests
on:
    schedule:
        # Runs every hour on the hour
        - cron: '0 * * * *'
    push:
      branches:
        - main
    pull_request:
      branches:
      types:
        - ready_for_review
        - opened
        - reopened
        - synchronize
    workflow_dispatch:

jobs:
  chaos-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'

    - name: Download dependencies
      run: go mod download

    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: Run chaos tests
      run: go vet ./... && gotestsum -- -v -race -count=1 ./...
      working-directory: ./chaos_tests
      env:
        PGPASSWORD: a!b@c$d()e*_,/:;=?@ff[]22
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}