name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (leave empty to auto-increment)'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating tags and branches

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history and tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FLAGS=""

          # Add version flag if provided
          if [ -n "${{ inputs.version }}" ]; then
            FLAGS="$FLAGS -version=${{ inputs.version }}"
          fi

          go run make_release.go -repo=. $FLAGS
